name: Release Builds

on:
  push:
    tags:
      - "*.*.*"

permissions: read-all

jobs:
  source:
    name: Source Code Releasing
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
      - name: Builds
        id: builds
        run: |
          tag=$(echo "$GITHUB_REF" | sed 's@^refs/tags/@@')
          packagename="mruby-$tag"
          destdir=packages

          mkdir -p "$destdir"
          git archive --format zip --prefix "$packagename/" -o "$destdir/$packagename.zip" "$GITHUB_REF"
          git archive --format tar.gz --prefix "$packagename/" -o "$destdir/$packagename.tar.gz" "$GITHUB_REF"
          gunzip -c "$destdir/$packagename.tar.gz" | xz > "$destdir/$packagename.tar.xz"

          (
            cd "$destdir"
            sha256sum * > .sha256
            mv .sha256 "$packagename.sha256"
          )
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          #draft: true
          prerelease: ${{ contains(github.ref, '-rc') }}
          body_path: NEWS
          files: packages/*
